// Définition des composants Storyblok (schémas envoyés par le bootstrap).
// C'est LA référence des blocs : nom technique, nom affiché, champs typés.

/* helpers */
const text = (display_name, extra = {}) => ({ type: "text", display_name, ...extra });
const textarea = (display_name, extra = {}) => ({ type: "textarea", display_name, ...extra });
const boolean = (display_name, extra = {}) => ({ type: "boolean", display_name, ...extra });
const asset = (display_name, extra = {}) => ({ type: "asset", filetypes: ["images"], display_name, ...extra });
const richtext = (display_name, extra = {}) => ({ type: "richtext", display_name, ...extra });
const bloks = (display_name, whitelist, extra = {}) => ({
  type: "bloks",
  display_name,
  restrict_components: true,
  component_whitelist: whitelist,
  ...extra,
});
const option = (display_name, options, extra = {}) => ({
  type: "option",
  display_name,
  options: options.map(([value, name]) => ({ value, name })),
  ...extra,
});

const MINI_FORMAT = "Astuce : *mot* → italique décoratif, retour à la ligne conservé.";

const ICON_OPTIONS = [
  ["phone", "Téléphone"],
  ["map-pin", "Épingle carte"],
  ["mail", "Enveloppe"],
  ["clock", "Horloge"],
  ["arrow-right", "Flèche droite"],
  ["check", "Coche"],
  ["chevron-down", "Chevron bas"],
  ["star", "Étoile"],
  ["bell", "Cloche"],
  ["coffee", "Machine à café"],
  ["medal", "Médaille"],
  ["shield", "Bouclier"],
  ["pin-check", "Épingle coche"],
  ["users", "Personnes"],
  ["file-invoice", "Facture"],
  ["file-text", "Document"],
  ["wrench", "Clé à molette"],
  ["check-circle", "Coche cercle"],
  ["globe", "Globe"],
];

const ILLUSTRATION_FIELDS = {
  illustration: option("Illustration décorative", [
    ["", "Aucune"],
    ["moka", "Cafetière moka"],
    ["grains", "Grains de café"],
    ["tasse", "Tasse"],
    ["plant", "Plant de café"],
    ["croissant", "Croissant"],
  ]),
  illustration_position: option("Position de l'illustration", [
    ["right", "Droite"],
    ["left", "Gauche"],
    ["corner-br", "Coin bas-droit"],
  ]),
  illustration_size: option("Taille de l'illustration", [
    ["sm", "Petite"],
    ["md", "Moyenne"],
    ["lg", "Grande"],
  ]),
};

const DELAY = text("Délai d'animation (1-4, vide = aucun)", {
  description: "Décalage de l'apparition au scroll, comme sur le site d'origine.",
});

const IMAGE_DIMS = {
  image_width: text("Largeur HTML de l'image (px)"),
  image_height: text("Hauteur HTML de l'image (px)"),
};

const SECTION_WHITELIST = [
  "hero_home",
  "page_hero",
  "landing_hero",
  "part_hero",
  "chr_hero",
  "stats_section",
  "universes_section",
  "products_home_section",
  "espresso_text_section",
  "certifications_section",
  "reassurance_section",
  "steps_section",
  "pricing_section",
  "b2b_section",
  "cta_section",
  "quote_form_section",
  "chr_products_section",
  "chr_extras_section",
  "gamme_filters",
  "pricing_note",
  "gamme_section",
  "part_products_section",
  "pastries_section",
  "part_contact_section",
  "contact_section",
  "faq_section",
  "about_story_section",
  "roasters_section",
  "cert_cards_section",
  "airpur_section",
  "legal_section",
  "sticky_cta",
];

/* ---------------- composants ---------------- */

export const GROUPS = ["Pages", "Sections", "Éléments"];

export const COMPONENTS = [
  {
    name: "page",
    display_name: "Page",
    is_root: true,
    is_nestable: false,
    group: "Pages",
    schema: {
      body: bloks("Sections de la page", SECTION_WHITELIST),
      "tab-seo": { type: "tab", display_name: "SEO", keys: ["seo_title", "seo_description", "og_title", "og_description", "breadcrumb_label", "breadcrumb_path", "jsonld"] },
      seo_title: text("Titre SEO (onglet navigateur / Google)"),
      seo_description: textarea("Description SEO"),
      og_title: text("Titre de partage (réseaux sociaux)"),
      og_description: textarea("Description de partage"),
      breadcrumb_label: text("Libellé du fil d'Ariane (vide = pas de fil d'Ariane)"),
      breadcrumb_path: text("Chemin de la page (rempli automatiquement)", { description: "Ex. /pages/contact — utilisé par le fil d'Ariane." }),
      jsonld: textarea("Données structurées JSON-LD (avancé — ne pas toucher)"),
      "tab-avance": { type: "tab", display_name: "Avancé", keys: ["style_scopes"] },
      style_scopes: {
        type: "options",
        display_name: "Styles de page chargés",
        description:
          "Laisser vide pour une nouvelle page : les styles sont choisis automatiquement selon les sections utilisées.",
        options: [
          { value: "home", name: "Accueil" },
          { value: "about", name: "À propos" },
          { value: "chr", name: "CHR" },
          { value: "contact", name: "Contact" },
          { value: "gamme", name: "Gamme" },
          { value: "landing", name: "Bureau (landing)" },
          { value: "particuliers", name: "Particuliers" },
        ],
      },
    },
  },
  {
    name: "site_settings",
    display_name: "Réglages du site (header, footer, contact)",
    is_root: true,
    is_nestable: false,
    group: "Pages",
    schema: {
      logo: asset("Logo"),
      phone: text("Numéro de téléphone principal"),
      cta_label: text("Bouton d'en-tête — texte"),
      cta_link: text("Bouton d'en-tête — lien"),
      nav_links: bloks("Liens du menu", ["nav_link"]),
      mobile_menu_cta_label: text("Menu mobile — bouton texte"),
      mobile_menu_cta_link: text("Menu mobile — bouton lien"),
      "tab-footer": { type: "tab", display_name: "Pied de page", keys: ["footer_desc", "footer_nav_heading", "footer_nav_links", "footer_cafes_heading", "footer_cafes_links", "footer_contact_heading", "address", "email", "hours", "copyright", "legal_label", "legal_link", "privacy_label", "privacy_link"] },
      footer_desc: textarea("Texte de présentation"),
      footer_nav_heading: text("Titre colonne navigation"),
      footer_nav_links: bloks("Liens colonne navigation", ["nav_link"]),
      footer_cafes_heading: text("Titre colonne cafés"),
      footer_cafes_links: bloks("Liens colonne cafés", ["nav_link"]),
      footer_contact_heading: text("Titre colonne contact"),
      address: text("Adresse"),
      email: text("Email"),
      hours: text("Horaires"),
      copyright: text("Ligne de copyright"),
      legal_label: text("Lien mentions légales — texte"),
      legal_link: text("Lien mentions légales — URL"),
      privacy_label: text("Lien confidentialité — texte"),
      privacy_link: text("Lien confidentialité — URL"),
    },
  },

  /* ----- éléments ----- */
  {
    name: "nav_link",
    display_name: "Lien de navigation",
    group: "Éléments",
    schema: {
      label: text("Texte"),
      link: text("Lien (ex. /pages/contact)"),
      hidden: boolean("Masqué (lien présent mais invisible)"),
    },
  },
  {
    name: "button",
    display_name: "Bouton",
    group: "Éléments",
    schema: {
      label: text("Texte"),
      link: text("Lien (URL, ancre #… ou tel:…)"),
      style: option("Style", [
        ["primary", "Principal (caramel)"],
        ["secondary", "Secondaire (contour)"],
        ["white", "Blanc"],
        ["white-outline", "Contour blanc"],
      ]),
      size: option("Taille", [
        ["", "Normale"],
        ["lg", "Grande"],
        ["sm", "Petite"],
      ]),
      icon: option("Icône", [["none", "Aucune"], ...ICON_OPTIONS]),
      location: text("Repère de tracking (data-location)"),
      phone_svg: boolean("Numéro de téléphone du texte rendu en image (anti-spam)"),
      extra_style: text("Styles CSS additionnels (avancé)"),
    },
  },
  {
    name: "stat_item",
    display_name: "Chiffre clé",
    group: "Éléments",
    schema: { number: text("Chiffre"), label: text("Légende"), delay: DELAY },
  },
  {
    name: "universe_card",
    display_name: "Carte univers (accueil)",
    group: "Éléments",
    schema: {
      image: asset("Image"),
      ...IMAGE_DIMS,
      badge: text("Badge (optionnel)"),
      title: text("Titre"),
      text: textarea("Texte"),
      button_label: text("Bouton — texte"),
      button_link: text("Bouton — lien"),
      button_style: option("Bouton — style", [
        ["primary", "Principal"],
        ["secondary", "Secondaire"],
      ]),
      hidden: boolean("Carte masquée"),
      delay: DELAY,
    },
  },
  {
    name: "product_card",
    display_name: "Produit",
    group: "Éléments",
    schema: {
      display_name: text("Nom affiché"),
      display_subtitle: text("Sous-titre affiché"),
      display_desc: textarea("Description courte affichée"),
      display_format: text("Format affiché"),
      display_price: text("Prix affiché"),
      price_small: text("Complément de prix en petit (ex. (0,45 €/pod))"),
      price_detail: text("Détail de prix (ligne dessous)"),
      badge_label: text("Badge — texte"),
      badge_style: option("Badge — style", [
        ["gold", "Doré"],
        ["simple", "Simple"],
      ]),
      medals_label: text("Ligne médailles (ex. 7 médailles ICT)"),
      seasonal_note: text("Note saisonnière (pâtisseries)"),
      image: asset("Photo"),
      ...IMAGE_DIMS,
      categories: text("Catégories de filtre (séparées par des espaces)", {
        description: "Pour la page gamme : grain, moulu, pods, grands-crus, bio, patisseries",
      }),
      patisserie_style: boolean("Style carte pâtisserie (page gamme)"),
      delay: DELAY,
      "tab-fiche": { type: "tab", display_name: "Fiche détaillée (fenêtre au clic)", keys: ["name", "subtitle", "description", "acidity", "body", "intensity", "roast", "notes", "origins", "certifications", "medals", "caffeine", "ingredients", "ingredients_glaze", "weight", "packaging", "order_period", "format", "price", "machine_info"] },
      name: text("Nom (la fiche ne s'ouvre que s'il est rempli)"),
      subtitle: text("Sous-titre"),
      description: textarea("Description complète"),
      acidity: text("Acidité (1 à 5)"),
      body: text("Corps (1 à 5)"),
      intensity: text("Intensité (1 à 5)"),
      roast: text("Torréfaction"),
      notes: text("Notes aromatiques (séparées par des virgules)"),
      origins: text("Origines"),
      certifications: text("Certifications (séparées par des virgules)"),
      medals: text("Années de médailles"),
      caffeine: text("Caféine"),
      ingredients: textarea("Ingrédients"),
      ingredients_glaze: textarea("Glaçage"),
      weight: text("Poids"),
      packaging: text("Emballage"),
      order_period: text("Période de commande"),
      format: text("Format"),
      price: text("Prix"),
      machine_info: textarea("Info machine (encart)"),
      "tab-tarifs": { type: "tab", display_name: "Tableau tarifs (page Bureau)", keys: ["table_desc", "table_format", "table_price", "table_unit", "table_badge_label", "table_badge_style", "card_desc", "card_amount", "card_unit", "card_badge_label", "card_badge_style"] },
      table_desc: text("Tableau — description"),
      table_format: text("Tableau — format"),
      table_price: text("Tableau — prix"),
      table_unit: text("Tableau — prix unitaire"),
      table_badge_label: text("Tableau — badge"),
      table_badge_style: option("Tableau — style badge", [
        ["gold", "Doré"],
        ["simple", "Simple"],
      ]),
      card_desc: text("Carte mobile — description"),
      card_amount: text("Carte mobile — montant"),
      card_unit: text("Carte mobile — unité"),
      card_badge_label: text("Carte mobile — badge"),
      card_badge_style: option("Carte mobile — style badge", [
        ["gold", "Doré"],
        ["simple", "Simple"],
      ]),
    },
  },
  {
    name: "product_group",
    display_name: "Groupe de produits (particuliers)",
    group: "Éléments",
    schema: {
      title: text("Titre du groupe"),
      products: bloks("Produits", ["product_card"]),
      note: textarea("Note sous le groupe (optionnel)"),
    },
  },
  {
    name: "reassurance_item",
    display_name: "Élément de réassurance",
    group: "Éléments",
    schema: {
      icon: option("Icône", ICON_OPTIONS),
      title: text("Titre"),
      text: textarea("Texte"),
      delay: DELAY,
    },
  },
  {
    name: "step_item",
    display_name: "Étape",
    group: "Éléments",
    schema: { title: text("Titre"), text: textarea("Texte"), delay: DELAY },
  },
  {
    name: "b2b_card",
    display_name: "Carte argument",
    group: "Éléments",
    schema: {
      icon: option("Icône", ICON_OPTIONS),
      title: text("Titre"),
      text: textarea("Texte"),
      delay: DELAY,
    },
  },
  {
    name: "trust_item",
    display_name: "Élément de confiance (héros)",
    group: "Éléments",
    schema: { text: text("Texte") },
  },
  {
    name: "certification_badge",
    display_name: "Badge certification",
    group: "Éléments",
    schema: { name: text("Nom"), caption: text("Légende") },
  },
  {
    name: "cert_card",
    display_name: "Carte certification",
    group: "Éléments",
    schema: {
      icon: option("Icône", ICON_OPTIONS),
      title: text("Titre"),
      text: textarea("Texte"),
      delay: DELAY,
    },
  },
  {
    name: "roaster_card",
    display_name: "Carte torréfacteur",
    group: "Éléments",
    schema: {
      name: text("Nom"),
      since: text("Depuis (ex. Depuis 1936)"),
      text: textarea("Paragraphes (séparés par une ligne vide)"),
      blends_title: text("Titre de la liste des mélanges"),
      blends: bloks("Mélanges", ["blend_item"]),
      delay: DELAY,
    },
  },
  {
    name: "blend_item",
    display_name: "Mélange",
    group: "Éléments",
    schema: { name: text("Nom (en gras)"), text: text("Description (après le tiret)") },
  },
  {
    name: "trait_item",
    display_name: "Caractéristique (Air Pur)",
    group: "Éléments",
    schema: { label: text("Libellé"), desc: text("Description") },
  },
  {
    name: "extra_card",
    display_name: "Carte complément (CHR)",
    group: "Éléments",
    schema: {
      image: asset("Image (optionnelle)"),
      title: text("Titre"),
      text: textarea("Paragraphes (séparés par une ligne vide)"),
      note: textarea("Note (en italique)"),
      button_label: text("Bouton — texte"),
      button_link: text("Bouton — lien"),
      delay: DELAY,
    },
  },
  {
    name: "faq_item",
    display_name: "Question / réponse",
    group: "Éléments",
    schema: { question: text("Question"), answer: textarea("Réponse"), delay: DELAY },
  },
  {
    name: "filter_item",
    display_name: "Filtre de gamme",
    group: "Éléments",
    schema: {
      label: text("Texte du bouton"),
      filter_key: text("Clé de filtre (all, grain, moulu, pods, grands-crus, bio, patisseries)"),
    },
  },

  /* ----- sections ----- */
  {
    name: "hero_home",
    display_name: "Héros — Accueil",
    group: "Sections",
    schema: {
      badge_logo: asset("Petit logo au-dessus du titre"),
      badge_text: text("Badge"),
      title: text("Titre", { description: MINI_FORMAT }),
      subtitle: textarea("Sous-titre"),
      buttons: bloks("Boutons", ["button"]),
    },
  },
  {
    name: "page_hero",
    display_name: "Héros — Bandeau simple",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      text: textarea("Texte"),
    },
  },
  {
    name: "landing_hero",
    display_name: "Héros — Bureau & Entreprise",
    group: "Sections",
    schema: {
      badge_text: text("Badge (avec étoile)"),
      title: text("Titre", { description: MINI_FORMAT }),
      subtitle: textarea("Sous-titre"),
      buttons: bloks("Boutons", ["button"]),
      trust_items: bloks("Éléments de confiance", ["trust_item"]),
      image: asset("Image"),
      ...IMAGE_DIMS,
    },
  },
  {
    name: "part_hero",
    display_name: "Héros — Particuliers",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      buttons: bloks("Boutons", ["button"]),
      image: asset("Image"),
      ...IMAGE_DIMS,
    },
  },
  {
    name: "chr_hero",
    display_name: "Héros — CHR",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre (les numéros de téléphone deviennent des liens)"),
      buttons: bloks("Boutons", ["button"]),
    },
  },
  {
    name: "stats_section",
    display_name: "Bandeau chiffres clés",
    group: "Sections",
    schema: {
      items: bloks("Chiffres", ["stat_item"]),
      ...ILLUSTRATION_FIELDS,
    },
  },
  {
    name: "universes_section",
    display_name: "Section univers (accueil)",
    group: "Sections",
    schema: {
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      cards: bloks("Cartes", ["universe_card"]),
    },
  },
  {
    name: "products_home_section",
    display_name: "Section produits — Accueil",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      products: bloks("Produits", ["product_card"]),
      cta_label: text("Bouton bas — texte"),
      cta_link: text("Bouton bas — lien"),
    },
  },
  {
    name: "espresso_text_section",
    display_name: "Section texte fond espresso",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      text: textarea("Paragraphes (séparés par une ligne vide)"),
      buttons: bloks("Boutons", ["button"]),
    },
  },
  {
    name: "certifications_section",
    display_name: "Bandeau certifications (accueil)",
    group: "Sections",
    schema: {
      title: text("Titre"),
      items: bloks("Certifications", ["certification_badge"]),
    },
  },
  {
    name: "reassurance_section",
    display_name: "Bandeau réassurance",
    group: "Sections",
    schema: { items: bloks("Éléments", ["reassurance_item"]) },
  },
  {
    name: "steps_section",
    display_name: "Section étapes (Comment ça marche)",
    group: "Sections",
    schema: {
      anchor_id: text("Ancre (id de section, ex. comment-ca-marche)"),
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      steps: bloks("Étapes", ["step_item"]),
    },
  },
  {
    name: "pricing_section",
    display_name: "Section tarifs (tableau, page Bureau)",
    group: "Sections",
    schema: {
      anchor_id: text("Ancre"),
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      products: bloks("Produits", ["product_card"]),
      note: text("Note sous le tableau"),
      cta_label: text("Bouton — texte"),
      cta_link: text("Bouton — lien"),
    },
  },
  {
    name: "b2b_section",
    display_name: "Section arguments (Pourquoi nous)",
    group: "Sections",
    schema: {
      background: option("Fond", [
        ["default", "Blanc cassé"],
        ["cream", "Crème"],
      ]),
      badge: text("Badge (optionnel)"),
      title: text("Titre"),
      grid_margin_top: boolean("Espace réduit sous le titre (variante particuliers)"),
      cards: bloks("Cartes", ["b2b_card"]),
    },
  },
  {
    name: "cta_section",
    display_name: "Bandeau d'appel à l'action",
    group: "Sections",
    schema: {
      theme: option("Thème", [
        ["cream", "Crème"],
        ["espresso", "Espresso (foncé)"],
      ]),
      title: text("Titre"),
      text: textarea("Texte"),
      buttons: bloks("Boutons", ["button"]),
    },
  },
  {
    name: "quote_form_section",
    display_name: "Section formulaire (devis / dégustation)",
    group: "Sections",
    schema: {
      variant: option("Champs du formulaire", [
        ["contact_rapide", "Contact rapide (accueil)"],
        ["degustation_bureau", "Dégustation bureau"],
        ["degustation_chr", "Dégustation CHR"],
      ]),
      style_variant: option("Fond de section", [
        ["cream_home", "Crème (accueil)"],
        ["plain", "Blanc cassé (bureau)"],
        ["cream_chr", "Crème (CHR)"],
      ]),
      anchor_id: text("Ancre"),
      form_name: text("Nom technique du formulaire (tracking)"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      phone_label: text("Libellé au-dessus du téléphone"),
      phone: text("Numéro de téléphone"),
      phone_location: text("Repère de tracking du téléphone"),
      phone_hours: text("Horaires sous le téléphone"),
      separator: text("Texte séparateur"),
      submit_label: text("Bouton d'envoi"),
      note: textarea("Note de consentement"),
      success_title: text("Message de succès — titre"),
      success_text: textarea("Message de succès — texte"),
    },
  },
  {
    name: "chr_products_section",
    display_name: "Section produits — CHR",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      products: bloks("Produits", ["product_card"]),
      cta_label: text("Bouton bas — texte"),
      cta_link: text("Bouton bas — lien"),
    },
  },
  {
    name: "chr_extras_section",
    display_name: "Section compléments (CHR)",
    group: "Sections",
    schema: {
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      cards: bloks("Cartes", ["extra_card"]),
    },
  },
  {
    name: "gamme_filters",
    display_name: "Filtres de la gamme",
    group: "Sections",
    schema: { items: bloks("Filtres", ["filter_item"]) },
  },
  {
    name: "pricing_note",
    display_name: "Note de prix (bandeau)",
    group: "Sections",
    schema: { text: text("Texte") },
  },
  {
    name: "gamme_section",
    display_name: "Section de gamme (catalogue)",
    group: "Sections",
    schema: {
      anchor_id: text("Ancre (ex. grains)"),
      section_cat: text("Catégorie de filtre de la section"),
      title: text("Titre"),
      intro: textarea("Introduction"),
      products: bloks("Produits", ["product_card"]),
    },
  },
  {
    name: "part_products_section",
    display_name: "Section produits — Particuliers",
    group: "Sections",
    schema: {
      badge: text("Badge"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      groups: bloks("Groupes de produits", ["product_group"]),
    },
  },
  {
    name: "pastries_section",
    display_name: "Section pâtisseries (particuliers)",
    group: "Sections",
    schema: {
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      cards: bloks("Pâtisseries", ["product_card"]),
    },
  },
  {
    name: "part_contact_section",
    display_name: "Section contact — Particuliers",
    group: "Sections",
    schema: {
      anchor_id: text("Ancre"),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      phone_title: text("Titre du bloc téléphone"),
      phone: text("Numéro de téléphone"),
      phone_location: text("Repère de tracking"),
      hours_text: text("Ligne horaires"),
      advice_text: textarea("Ligne conseil"),
      email: text("Email"),
      submit_label: text("Bouton d'envoi"),
      note: textarea("Note de consentement"),
      success_title: text("Succès — titre"),
      success_text: textarea("Succès — texte"),
    },
  },
  {
    name: "contact_section",
    display_name: "Section contact (formulaire + infos)",
    group: "Sections",
    schema: {
      form_title: text("Formulaire — titre"),
      form_intro: textarea("Formulaire — introduction"),
      submit_label: text("Bouton d'envoi"),
      note: textarea("Note de consentement"),
      success_title: text("Succès — titre"),
      success_text: textarea("Succès — texte"),
      "tab-infos": { type: "tab", display_name: "Colonne infos", keys: ["info_title", "address", "phone", "phone_location", "email", "hours", "zone_title", "zone_text", "degust_title", "degust_text", "degust_button_label", "degust_button_link", "map_heading", "map_url", "map_title"] },
      info_title: text("Titre coordonnées"),
      address: text("Adresse"),
      phone: text("Téléphone"),
      phone_location: text("Repère de tracking"),
      email: text("Email"),
      hours: text("Horaires"),
      zone_title: text("Titre zone de livraison"),
      zone_text: textarea("Texte zone de livraison"),
      degust_title: text("Titre dégustation"),
      degust_text: textarea("Texte dégustation"),
      degust_button_label: text("Bouton dégustation — texte"),
      degust_button_link: text("Bouton dégustation — lien"),
      map_heading: text("Titre carte"),
      map_url: textarea("URL d'intégration Google Maps"),
      map_title: text("Titre accessible de la carte"),
    },
  },
  {
    name: "faq_section",
    display_name: "Section FAQ",
    group: "Sections",
    schema: {
      title: text("Titre"),
      ...ILLUSTRATION_FIELDS,
      items: bloks("Questions", ["faq_item"]),
    },
  },
  {
    name: "about_story_section",
    display_name: "Section histoire (à propos)",
    group: "Sections",
    schema: {
      title: text("Titre"),
      text: textarea("Paragraphes (séparés par une ligne vide)"),
      image: asset("Image"),
      ...IMAGE_DIMS,
      quote: text("Citation"),
      quote_author: text("Auteur de la citation"),
    },
  },
  {
    name: "roasters_section",
    display_name: "Section torréfacteurs",
    group: "Sections",
    schema: {
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      ...ILLUSTRATION_FIELDS,
      roasters: bloks("Torréfacteurs", ["roaster_card"]),
    },
  },
  {
    name: "cert_cards_section",
    display_name: "Section certifications / récompenses",
    group: "Sections",
    schema: {
      background: option("Fond", [
        ["default", "Blanc cassé"],
        ["cream", "Crème"],
      ]),
      title: text("Titre"),
      subtitle: textarea("Sous-titre"),
      cards: bloks("Cartes", ["cert_card"]),
    },
  },
  {
    name: "airpur_section",
    display_name: "Section torréfaction Air Pur",
    group: "Sections",
    schema: {
      title: text("Titre"),
      text: textarea("Paragraphes (séparés par une ligne vide)"),
      traits: bloks("Caractéristiques", ["trait_item"]),
    },
  },
  {
    name: "legal_section",
    display_name: "Contenu mentions légales",
    group: "Sections",
    schema: {
      title: text("Titre de la page"),
      content_mentions: richtext("Mentions légales"),
      rgpd_title: text("Titre politique de confidentialité"),
      content_rgpd: richtext("Politique de confidentialité"),
      back_label: text("Lien retour — texte"),
      back_link: text("Lien retour — URL"),
      phone: text("Numéro affiché en image anti-spam"),
    },
  },
  {
    name: "sticky_cta",
    display_name: "Barre d'action mobile (bas d'écran)",
    group: "Sections",
    schema: {
      call_label: text("Bouton appel — texte"),
      call_link: text("Bouton appel — lien tel:"),
      contact_label: text("Bouton contact — texte"),
      contact_link: text("Bouton contact — lien"),
    },
  },
];
